extends: stylelint-config-sass-guidelines
rules:
  max-nesting-depth: 2
  selector-max-id: 1
  selector-no-qualifying-type: null
  scss/at-import-no-partial-leading-underscore: null
  "@stylistic/string-quotes": double
