# Site settings
title: Andreas Mausch
email: andreas.mausch@gmail.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: ""
url: "https://andreas-mausch.de"

# Build settings
markdown: kramdown
permalink: pretty

collections:
  cheatsheets:
    output: true
    permalink: /:collection/:name
