# Site settings
title: Andreas Mausch
email: andreas.mausch@gmail.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: ""
url: "http://andreas-mausch.de"
twitter_username:
github_username:

# Build settings
markdown: kramdown
