# Site settings
title: Andreas Mausch
email: andreas.mausch@gmail.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: ""
url: "http://andreas-mausch.de"

# Build settings
markdown: kramdown
permalink: pretty
