name: Deploy Eleventy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # Graphviz is needed for more complex PlantUML diagrams
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v2

      - name: Install dependencies & build
        run: |
          npm ci
          npm run lint
          npm run check
          ELEVENTY_PATH_PREFIX=/eleventy-sample npm run build -- --pathprefix=/eleventy-sample

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./_site
          github_token: ${{ secrets.GITHUB_TOKEN }}
